### ISSUE TITLE
Fetching api keys in runtime

### ISSUE THREAD

**Issue by teamon** [ahtung/onesky.ex#14]
Hi, thanks for using tesla! 😊

I’ve noticed you assign api keys from application env into module attributes. I’d recommend calling `Application.get_env/2` inside `client` function so that api let’s can be read in runtime when running inside a compiled distillery release.

**Comment by dunyakirkali** [comment]
@teamon I don't know how but somehow it took me a year to see your comment 😬 
Sorry for that.

This will be fixed in https://github.com/ahtung/onesky.ex/pull/18

And Thnx for creating [tesla](https://github.com/teamon/tesla) ;)
